---
name: Vendor Dependencies Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - 'justfile'
      - 'aqua/**'
      - '.github/workflows/**'

jobs:
  depscheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: aquaproj/aqua-installer@a78671ff723534c879a9c8aa62c99a3a05dddb49 # v4.0.5
        with:
          aqua_version: v2.61.0
          aqua_opts: ''
        env:
          AQUA_GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - run: aqua -c aqua/aqua.yml exec -- just depscheck
